// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evxteoxxkjiidmgqypdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2eHRlb3h4a2ppaWRtZ3F5cGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTQ2NzQsImV4cCI6MjA2NTk5MDY3NH0.xoTAyCsXoEQI6_sKjH_91EdrlARh2vhS1yytTmp-0Vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);